### ISSUE TITLE
Install was crashed said Failed at the fuel-ui@0.3.9 postinstall script 'bower install && typings install'.

### ISSUE THREAD

**Issue by KeroVieux** [FuelInteractive/fuel-ui#106]
My evnt. is 

>  node v4.5.0
> npm  v3.10.3
> bower@1.7.9 
> typings@1.3.3 

When I install fuel-ui as below

> npm install fuel-ui

I've got a error like this:

> npm WARN fuel-ui@0.3.9 requires a peer of zone.js@0.6.12 but none was installed.
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
> npm ERR! node v4.5.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! fuel-ui@0.3.9 postinstall: `bower install && typings install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fuel-ui@0.3.9 postinstall script 'bower install && typings install'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the fuel-ui package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     bower install && typings install
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs fuel-ui
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls fuel-ui
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/kerovieux/webProject/testWebapp/ng-fuel-cli/npm-debug.log

What can I do to resolve...

**Comment by georgianacazacu** [comment]
any solution here? I have the some problem.

**Comment by jacobedawson** [comment]
First time trying out fuel-ui, running into the same issue.

**Comment by rafaelcoutinho** [comment]
It looks like it is missing 'typings' definition manager (or a dependency to it).
I have fixed it by installing typings manually:
`npm install typings --global`
it solves that issue, but now i'm getting another issue related to typings + npm : 
```/usr/local/lib/node_modules/typings/node_modules/typings-core/node_modules/strip-bom/index.js:2
module.exports = x => {
                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/typings/node_modules/typings-core/dist/utils/fs.js:5:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

There is a question on stackoverflow, but updating npm did not solve it:
[Typings: SyntaxError: Unexpected token =>](http://stackoverflow.com/questions/41186240/typings-syntaxerror-unexpected-token)

There is also another thread here that seems to be related: 
[Gulp-Sourcemaps, SyntaxError: Unexpected token >](http://stackoverflow.com/questions/40220506/gulp-sourcemaps-syntaxerror-unexpected-token)

but did not work so far, getting the error below:
```
/usr/local/lib/node_modules/typings/node_modules/typings-core/node_modules/popsicle/dist/common.js:20
    var defaults = Object.assign({}, { transport: transport }, defaultsOptions
                          ^
TypeError: undefined is not a function
    at defaults (/usr/local/lib/node_modules/typings/node_modules/typings-core/node_modules/popsicle/dist/common.js:20:27)
```

**Comment by rafaelcoutinho** [comment]
Well cloning the clean project works
https://github.com/coryshaw1/ng2-play/

Maybe my project has some not compatible dependencies.

**Comment by chenyouyee** [comment]
I ran into the same problem so I tried installing bowers and typings manually (in that order; did not have either installed beforehand). Tried fuel-ui install again, and this time it completed with no issues. No idea why this would work, but maybe this will work for someone else too. I was installing on Windows, if that's relevant

**Comment by Majed93** [comment]
I installed bower and typings globally and this error seemed to go away.
